# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
    core: ren/core@0.0.1

jobs:
    build:
        docker:
            - image: circleci/golang:1.12
        steps:
            - checkout
            - restore_cache:
                key: go-mod-v3-{{ checksum "go.sum" }}
            - run:
                name: Run tests
                command: |
                    make
            - save_cache:
                key: go-mod-v3-{{ checksum "go.sum" }}
                paths:
                    - "~/go"

    deploy:
        docker:
            - image: techknowlogick/xgo:latest
        steps:
            - checkout
            - run:
                name: Install tools
                command: |
                    go vet ./...
            - core/install_ghr
            - run:
                name: Build binaries
                command: |
                    make
                    mv $(make target_name) ./artifacts/darknode_linux_amd64
                    GOOS=linux CGO_ENABLED=1 CC=arm-linux-gnueabi-gcc-6 GOARCH=arm make
                    mv $(make target_name) ./artifacts/darknode_linux_arm
                    GOOS=darwin CGO_ENABLED=1 CC=o64-clang GOARCH=amd64 make
                    mv $(make target_name) ./artifacts/darknode_darwin_amd64
                    ls ./artifacts  # > files.txt
#           - core/github_release:
#               tag: $CIRCLE_TAG
#               replace: true
#               filelist: files.txt

workflows:
  version: 2.1

  build_release:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
